### ISSUE TITLE
Suggested refinement to the integration time argument code

### ISSUE THREAD

**Issue by davidbenncsiro** [StefanSimis/PyTrios#10]
Further to #5, as a further refinement to the integration time argument code, we could do something like this instead:
~~~
elif args.type == 1:
        permitted_inttimes = [2**n for n in range(3, 14)]
        if args.inttime != 0 and args.inttime not in permitted_inttimes:
                log.info("Integration time for G1 sensors must be 0 (auto) or one of {} ms",
                             ", ".join(permitted_inttimes))
                sys.exit()
    elif args.type == 2:
        permitted_inttimes = [2**n for n in range(2, 14)]
        if args.inttime != 0 and args.inttime not in permitted_inttimes:
                log.info("Integration time for G2 sensors must be 0 (auto) or one of {} ms",
                             ", ".join(permitted_inttimes))
...
~~~

**Comment by StefanSimis** [comment]
Has this been sufficiently addressed with https://github.com/StefanSimis/PyTrios/pull/9 ?

**Comment by davidbenncsiro** [comment]
This issue merely captures a possible refinement/refactoring of a section of the command-line handling code that occurred to me while I was addressing #5 (via #9).

It does not change the functionality at all, although would need to be tested against a device.

I am happy for you to say that you think this should be closed.

Over to you @StefanSimis. :)

**Comment by StefanSimis** [comment]
I have a slight preference for showing the list of options available to the user in full, since this cannot be easily resolved in the argparse, there being two cases for it. So will close this. 
As a side note, this script is only intended as a template for users to alter as they see fit in their own applications, and a quick test of the connect system. I didn't intend it as a complete interface, anyway :)
